# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'raza',
            },
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'especie',
            },
        ),
        migrations.CreateModel(
            name='Vac_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='tipo de vacuna')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripcion')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'tipo de vacuna',
                'verbose_name_plural': 'tipos de vacunas',
            },
        ),
        migrations.AddField(
            model_name='breed',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Specie'),
        ),
    ]
