from django.conf.urls import patterns, include, url
from .views import EditClient, ClientDetails, DeleteClient, EditPatient, DeletePatient, PatientDetails, BreedList, EditBreed, DeleteBreed, SpecieList, EditSpecie, DeleteSpecie, Vac_TypeList, EditVac_Type, DeleteVac_Type

urlpatterns = patterns('',
    url(r'^clinica/pacientes/$', 'clinic.views.patients_list', name='patients_list'),
    url(r'^clinica/paciente/(?P<pk>\d+)/$', PatientDetails.as_view(), name='patient_details'),
    url(r'^clinica/paciente/(?P<pk>\d+)/consulta/$', 'clinic.views.add_consult', name='register_consult'),
    url(r'^clinica/paciente/(?P<pk>\d+)/vacuna/$', 'clinic.views.add_vaccine', name='register_vaccine'),
    url(r'^clinica/paciente/(?P<pk>\d+)/desparasitacion/$', 'clinic.views.add_deworming', name='register_deworming'),
    url(r'^clinica/paciente/(?P<pk>\d+)/complementarios/$', 'clinic.views.add_complementary', name='register_complementary'),
    url(r'^clinica/paciente/editar/(?P<pk>\d+)/$', EditPatient.as_view(), name='edit_patient'),
    url(r'^clinica/paciente/borrar/(?P<pk>\d+)/$', DeletePatient.as_view(), name='delete_patient'),
    url(r'^clinica/cliente/(?P<pk>\d+)/paciente/nuevo/', 'clinic.views.add_patient', name='register_patient'),
    url(r'^clinica/clientes/$', 'clinic.views.clients_list', name='clients_list'),
    url(r'^clinica/cliente/(?P<pk>\d+)/$', ClientDetails.as_view(), name='client_details'),
    url(r'^clinica/cliente/editar/(?P<pk>\d+)/$', EditClient.as_view(), name='edit_client'),
    url(r'^clinica/cliente/borrar/(?P<pk>\d+)/$', DeleteClient.as_view(), name='delete_client'),
    url(r'^clinica/clientes/nuevo/', 'clinic.views.add_client', name='register_client'),
    url(r'^clinica/conf/raza/$', BreedList.as_view(), name='breed_conf'),
    url(r'^clinica/conf/raza/nuevo/', 'clinic.views.add_breed', name='breed_conf_add'),
    url(r'^clinica/conf/raza/editar/(?P<pk>\d+)/$', EditBreed.as_view(), name='edit_breed'),
    url(r'^clinica/conf/raza/borrar/(?P<pk>\d+)/$', DeleteBreed.as_view(), name='delete_breed'),
    url(r'^clinica/conf/especie/$', SpecieList.as_view(), name='specie_conf'),
    url(r'^clinica/conf/especie/nuevo/', 'clinic.views.add_specie', name='specie_conf_add'),
    url(r'^clinica/conf/especie/editar/(?P<pk>\d+)/$', EditSpecie.as_view(), name='edit_specie'),
    url(r'^clinica/conf/especie/borrar/(?P<pk>\d+)/$', DeleteSpecie.as_view(), name='delete_specie'),
    url(r'^clinica/conf/tipo_vac/$', Vac_TypeList.as_view(), name='vac_conf'),
    url(r'^clinica/conf/tipo_vac/nuevo/', 'clinic.views.add_vac_type', name='vac_conf_add'),
    url(r'^clinica/conf/tipo_vac/editar/(?P<pk>\d+)/$', EditVac_Type.as_view(), name='edit_vac_type'),
    url(r'^clinica/conf/tipo_vac/borrar/(?P<pk>\d+)/$', DeleteVac_Type.as_view(), name='delete_vac_type'),
)
